<?php

require_one('Gacha.php');
//----------------------------
//データ準備
//----------------------------
$data = [
	['name'=>'太古の魔導書','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/book_003.png'],
	['name'=>'魔術王の書','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/book_004.png'],
	['name'=>'歴戦の戦斧','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe009.png'],
	['name'=>'ミスリルアックス','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe009b.png'],
	['name'=>'天啓の戦斧','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe010.png'],
	['name'=>'恩讐の戦斧','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe010b.png'],
	['name'=>'グレートアックス','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe011.png'],
	['name'=>'エクセレントアックス','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe011b.png'],
	['name'=>'殴打の斧','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe014.png'],
	['name'=>'ミスリル','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe014b.png'],
	['name'=>'ブレイズ','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe014c.png'],
	['name'=>'白銀の弓','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow001.png'],
	['name'=>'神血の弓','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow001b.png'],
	['name'=>'ドレッドボウ','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow001.png'],
	['name'=>'エルフ神の絶弓','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow001b.png'],
	['name'=>'忌憚弓','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow001.png'],
	['name'=>'禁忌大弓','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow001b.png'],
	['name'=>'マグロ、ご期待ください。','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_other_008.png'],
	['name'=>'覇王のまごのて','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_other_002.png'],
	['name'=>'魔槍シャクティ','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear016.png'],
	['name'=>'オリハルコンスパイク','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear017.png'],
	['name'=>'両刃の呪槍','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear017b.png'],
	['name'=>'エルフィン','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear018.png'],
	['name'=>'二の打ちいらず','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear019.png'],
	['name'=>'ヘルブレイズハルバード','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear019b.png'],




],
[
	['name'=>'中級魔導書','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/book_002b.png'],
	['name'=>'古い魔導書','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/book_002c.png'],
	['name'=>'鋼の斧','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe005.png'],
	['name'=>'フルメタルアックス','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe005b.png'],
	['name'=>'鋼鉄の斧','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe006.png'],
	['name'=>'鋼鉄の手斧','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe006b.png'],
	['name'=>'氷鋼の斧','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe006c.png'],
	['name'=>'エリートアックス','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe007.png'],
	['name'=>'優秀な手斧','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe007b.png'],
	['name'=>'優秀な消化斧','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe008.png'],
	['name'=>'地鋼の斧','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe008b.png'],
	['name'=>'炎鋼の斧','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe008c.png'],
	['name'=>'吹雪斧','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe008d.png'],
	['name'=>'猛毒斧','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe008e.png'],
	['name'=>'ハルバード','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe012.png'],
	['name'=>'ファイアハルバード','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe012b.png'],
	['name'=>'コールドハルバード','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe012c.png'],
	['name'=>'両刃の戦斧','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe013.png'],
	['name'=>'両刃の斧','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe013b.png'],
	['name'=>'吸血の戦斧','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe013c.png'],
	['name'=>'グレートボウ','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow008.png'],
	['name'=>'ブレイズボウ','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow008b.png'],
	['name'=>'黄金の弓','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow012.png'],
	['name'=>'氷獄弓','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow012b.png'],
	['name'=>'クロスボウ','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow013.png'],
	['name'=>'フレイムクロスボウ','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow013b.png'],
	['name'=>'グレートクロスボウ','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow014.png'],
	['name'=>'ブレイズクロスボウ','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow014b.png'],
	['name'=>'達人のクロスボウ','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow015.png'],
	['name'=>'エルフクロスボウ','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow015b.png'],
	['name'=>'リトルバリスタ','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow016.png'],
	['name'=>'城塞設置式バリスタ','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow016b.png'],
	['name'=>'スナイプボウ','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow017.png'],
	['name'=>'フライパン','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_other_007.png'],
	['name'=>'お土産クナイ','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_other_003.png'],
	['name'=>'チタンスピア','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear010.png'],
	['name'=>'ゴリアテ','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear010b.png'],
	['name'=>'ゴーレムスピア','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear011.png'],
	['name'=>'ミスリルスピア','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear011b.png'],
	['name'=>'アイアンスパイク','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear012.png'],
	['name'=>'氷像の槍','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear012b.png'],
	['name'=>'炎上槍','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear012c.png'],
	['name'=>'獄炎槍','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear013.png'],
	['name'=>'氷獄槍','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear013b.png'],
	['name'=>'絶毒槍','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear013c.png'],
	['name'=>'アースクエイクスピア','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear013d.png'],
	['name'=>'ブレイクアイス','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear014.png'],
	['name'=>'ブレイズデストロイ','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear014b.png'],
	['name'=>'ポイズンバーン','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear014c.png'],
	['name'=>'アースウェーブ','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear014d.png'],
	['name'=>'星霜の書','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear015.png'],
	['name'=>'薙刀','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear020.png'],
	['name'=>'パルチザン','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear020c.png'],



],
[
	['name'=>'見習い魔導書','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/book_001.png'],
	['name'=>'初級魔導書','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/book_002.png'],
	['name'=>'鉄の斧','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe001.png'],
	['name'=>'鉞','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe002.png'],
	['name'=>'炎の鉞','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe002b.png'],
	['name'=>'氷の鉞','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe002c.png'],
	['name'=>'毒の斧','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe002d.png'],
	['name'=>'大地の鉞','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe002e.png'],
	['name'=>'手斧','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe003.png'],
	['name'=>'ブラッドアクス','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe003b.png'],
	['name'=>'ククリみたいな手斧','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe004.png'],
	['name'=>'新緑の手斧','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe004b.png'],
	['name'=>'トンカチ','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe015.png'],
	['name'=>'赤色のトンカチ','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe015b.png'],
	['name'=>'ネイルハンマー','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe016.png'],
	['name'=>'つるはし','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe016b.png'],
	['name'=>'もはやハンマー','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe017.png'],
	['name'=>'むしろハンマー','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe017b.png'],
	['name'=>'装飾用の斧','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_axe018.png'],
	['name'=>'木の弓','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow001.png'],
	['name'=>'白樺の弓','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow001b.png'],
	['name'=>'木の大弓','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow002.png'],
	['name'=>'白樺の大弓','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow002b.png'],
	['name'=>'新緑の弓','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow003.png'],
	['name'=>'猛炎の弓','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow003b.png'],
	['name'=>'ラピッドボウ','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow004.png'],
	['name'=>'ナリキンボウ','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow004b.png'],
	['name'=>'狩人の弓','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow005.png'],
	['name'=>'血吸いの弓','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow005b.png'],
	['name'=>'エメラルドボウ','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow006.png'],
	['name'=>'サファイアボウ','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow006b.png'],
	['name'=>'ルビーボウ','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow007.png'],
	['name'=>'琥珀の弓','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_bow007b.png'],
	['name'=>'十手','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_other_001.png'],
	['name'=>'鎖鎌','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_other_004.png'],
	['name'=>'パチンコ','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_other_005.png'],
	['name'=>'ピコハン','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_other_006.png'],
	['name'=>'チェーンソー','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_other_009.png'],
	['name'=>'安物の槍','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear001.png'],
	['name'=>'鉄の槍','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear002.png'],
	['name'=>'グレートスピア','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear003.png'],
	['name'=>'トライデント','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear004.png'],
	['name'=>'フローズントライデント','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear004b.png'],
	['name'=>'大鎌','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear005.png'],
	['name'=>'死神の大鎌','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear005b.png'],
	['name'=>'スパイクスピア','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear006.png'],
	['name'=>'バーンスパイク','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear006b.png'],
	['name'=>'コールドスパイク','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear006c.png'],
	['name'=>'ポイズンスパイク','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear006d.png'],
	['name'=>'アーススパイク','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear006e.png'],
	['name'=>'達人の槍','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear007.png'],
	['name'=>'達人の大槍','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear007b.png'],
	['name'=>'ブレードスピア','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear008.png'],
	['name'=>'コールドブレードスピア','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear008b.png'],
	['name'=>'シャープスピア','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear009.png'],
	['name'=>'コールドシャープスピア','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear009b.png'],
	['name'=>'伝説の槍（偽）','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_spear020b.png'],
	['name'=>'木の枝','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_staff001.png'],
	['name'=>'木の棒','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_staff001b.png'],
	['name'=>'木の杖','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_staff001.png'],
	['name'=>'鉄製の杖','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_staff001b.png'],
	['name'=>'僧侶の杖','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_staff001.png'],
	['name'=>'アイアンスタッフ','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_staff001b.png'],
	['name'=>'賢者の杖','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_staff001.png'],
	['name'=>'悪魔の杖','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_staff001b.png'],
	['name'=>'聖者の杖','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_staff001.png'],
	['name'=>'木の棒','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_staff001b.png'],
	['name'=>'木の枝','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_staff001.png'],
	['name'=>'木の棒','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_staff001b.png'],
	['name'=>'木の枝','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_staff001.png'],
	['name'=>'木の棒','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_staff001b.png'],
	['name'=>'木の枝','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_staff001.png'],
	['name'=>'木の棒','HP'=>0,'ATK'=>1,'DEF'=>0,'SPD'=>1,'LUK'=>1,'EFFECT'=>0,'img'=>'GachaBuildersHost/GatyaResource/weapon/we_staff001b.png'],





];

$json = getGacha($data);

//----------------------------
//クライアントに出力
//----------------------------
header('Access-Control-Allow-Origin: *');
print $json;
?>
